####

- id: primary-network-node
  type: group
  role: [primary-network-node]
  requires: [deploy_start]
  required_for: [deploy_end]
  parameters:
    strategy:
      type: one_by_one

- id: network-node
  type: group
  role: [network-node]
  requires: [deploy_start, primary-network-node]
  required_for: [deploy_end]
  parameters:
    strategy:
      type: one_by_one

### Tasks
- id: network-node-task
  type: puppet
  groups: [primary-network-node, network-node]
  requires: [cluster, firewall]
  required_for: [deploy_end]
  parameters:
    puppet_manifest: /etc/puppet/modules/osnailyfacter/modular/openstack-network/openstack-network-controller.pp
    puppet_modules: /etc/puppet/modules
    timeout: 3600
